### ISSUE TITLE
Bridge api error-related messages need improvement

### ISSUE THREAD

**Issue by bryanchriswhite** [Storj/bridge-gui-vue#45]
Several users have reported this error: "Request failed with status code 400" when attempting to register an account. At least one cause of this message on the signup page is the result of that email already being registered (regardless of activation state). Here you see the UI error message compared to the bridge API's error message in dev tools:

![screenshot from 2018-02-12 18-39-48](https://user-images.githubusercontent.com/600733/36110894-9600992a-1024-11e8-8d05-a36a4137e6b8.png)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
